import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'
// import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const walletConnect = () =>{
  
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Ditributed Medical Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <nav>
          <div className='order-1'>
            aaa
          </div>
          
          <Link href={'https://httpbin.org/ip'} className='order-3'>
            your ip
          </Link>
        </nav>
        <h1 className="text-3xl font-bold underline">
          Hello world
        </h1>
      </div>
    </>
  )
}
