export const abi = [
    {
       "inputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"patient",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"viewer",
             "type":"address"
          }
       ],
       "name":"ApproveViewData",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"patient",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"viewer",
             "type":"address"
          }
       ],
       "name":"DisapproveViewData",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"doctor",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"timestamp",
             "type":"uint256"
          }
       ],
       "name":"DoctorRegistered",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"doctor",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"timestamp",
             "type":"uint256"
          }
       ],
       "name":"DoctorRemoved",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"from",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"address",
             "name":"to",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"Paid",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"patient",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"string",
             "name":"name",
             "type":"string"
          },
          {
             "indexed":false,
             "internalType":"enum Enum.BloodType",
             "name":"bloodType",
             "type":"uint8"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"lastUpdated",
             "type":"uint256"
          }
       ],
       "name":"PatientRegistered",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"address",
             "name":"patient",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"string",
             "name":"name",
             "type":"string"
          },
          {
             "indexed":false,
             "internalType":"enum Enum.BloodType",
             "name":"bloodType",
             "type":"uint8"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"lastUpdated",
             "type":"uint256"
          }
       ],
       "name":"PatientUpdated",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"previousAdminRole",
             "type":"bytes32"
          },
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"newAdminRole",
             "type":"bytes32"
          }
       ],
       "name":"RoleAdminChanged",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"account",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"sender",
             "type":"address"
          }
       ],
       "name":"RoleGranted",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"account",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"sender",
             "type":"address"
          }
       ],
       "name":"RoleRevoked",
       "type":"event"
    },
    {
       "inputs":[
          
       ],
       "name":"DEFAULT_ADMIN_ROLE",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_patient",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_viewer",
             "type":"address"
          }
       ],
       "name":"approveViewData",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_patient",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_viewer",
             "type":"address"
          }
       ],
       "name":"disapproveViewData",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_patient",
             "type":"address"
          }
       ],
       "name":"getApproved",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_patient",
             "type":"address"
          }
       ],
       "name":"getPatientData",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"string",
                   "name":"name",
                   "type":"string"
                },
                {
                   "internalType":"enum Enum.BloodType",
                   "name":"bloodType",
                   "type":"uint8"
                },
                {
                   "internalType":"uint256",
                   "name":"lastUpdated",
                   "type":"uint256"
                }
             ],
             "internalType":"struct MedicalDatabase.Patient",
             "name":"",
             "type":"tuple"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          }
       ],
       "name":"getRoleAdmin",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          }
       ],
       "name":"grantRole",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          }
       ],
       "name":"hasRole",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_patient",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_viewer",
             "type":"address"
          }
       ],
       "name":"isApproved",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_doctor",
             "type":"address"
          }
       ],
       "name":"isDoctor",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_to",
             "type":"address"
          }
       ],
       "name":"pay",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_doctor",
             "type":"address"
          }
       ],
       "name":"registerDoctor",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_patient",
             "type":"address"
          },
          {
             "internalType":"string",
             "name":"_name",
             "type":"string"
          },
          {
             "internalType":"enum Enum.BloodType",
             "name":"_bloodType",
             "type":"uint8"
          }
       ],
       "name":"registerPatient",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_doctor",
             "type":"address"
          }
       ],
       "name":"removeDoctor",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          }
       ],
       "name":"renounceRole",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"role",
             "type":"bytes32"
          },
          {
             "internalType":"address",
             "name":"account",
             "type":"address"
          }
       ],
       "name":"revokeRole",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes4",
             "name":"interfaceId",
             "type":"bytes4"
          }
       ],
       "name":"supportsInterface",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_patient",
             "type":"address"
          },
          {
             "internalType":"string",
             "name":"_name",
             "type":"string"
          },
          {
             "internalType":"enum Enum.BloodType",
             "name":"_bloodType",
             "type":"uint8"
          }
       ],
       "name":"updatePatient",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    }
 ]